version: '3.8'

services:
  # Test Graph Database (FalkorDB)
  falkordb-test:
    image: falkordb/falkordb:latest
    ports:
      - "6380:6379"
    command: ["falkordb", "--port", "6379", "--dir", "/data"]
    networks:
      - memento-test-network
    tmpfs:
      - /data
    restart: unless-stopped

  # Test Vector Database (Qdrant)
  qdrant-test:
    image: qdrant/qdrant:latest
    ports:
      - "6335:6333"
      - "6336:6334"
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - memento-test-network
    tmpfs:
      - /qdrant/storage
    restart: unless-stopped

  # Test Relational Database (PostgreSQL)
  postgres-test:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=memento_test
      - POSTGRES_USER=memento_test
      - POSTGRES_PASSWORD=memento_test
    networks:
      - memento-test-network
    tmpfs:
      - /var/lib/postgresql/data
    restart: unless-stopped

  # Test Redis for caching and session management
  redis-test:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - memento-test-network
    tmpfs:
      - /data
    restart: unless-stopped

networks:
  memento-test-network:
    driver: bridge
