version: '3.8'

services:
  # Main Memento API server
  memento-api:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"  # WebSocket port
    environment:
      - NODE_ENV=development
      - FALKORDB_URL=redis://falkordb:6379
      - QDRANT_URL=http://qdrant:6333
      - DATABASE_URL=postgresql://memento:memento@postgres:5432/memento
      - MCP_PORT=3002
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      - falkordb
      - qdrant
      - postgres
    networks:
      - memento-network
    restart: unless-stopped

  # Graph Database (FalkorDB)
  falkordb:
    image: falkordb/falkordb:latest
    ports:
      - "6379:6379"
    volumes:
      - falkordb_data:/data
    command: ["falkordb", "--port", "6379", "--dir", "/data"]
    networks:
      - memento-network
    restart: unless-stopped

  # Vector Database (Qdrant)
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - memento-network
    restart: unless-stopped

  # Relational Database (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=memento
      - POSTGRES_USER=memento
      - POSTGRES_PASSWORD=memento
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - memento-network
    restart: unless-stopped

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - memento-network
    restart: unless-stopped

volumes:
  falkordb_data:
    driver: local
  qdrant_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  memento-network:
    driver: bridge
