/**
 * Core Types and Interfaces for Memento
 * Domain-specific types that are unique to the core package
 */

// Re-export types from shared-types for backward compatibility
export type {
  HistoryConfig,
  CheckpointReason,
  CheckpointCreateRequest,
  TemporalGraphQuery,
  SessionChangeSummary,
  SessionChangesResult,
  SessionTimelineEvent,
  SessionTimelineSummary,
  SessionTimelineResult,
  SessionImpactEntry,
  SessionImpactsResult,
  SessionsAffectingEntityEntry,
  SessionsAffectingEntityResult,
  SessionMetadata,
  SessionQueryOptions,
  PerformanceHistoryOptions,
  PerformanceHistoryRecord,
  PerformanceMetrics,
  ValidationRequest,
  ValidationResult,
  ValidationIssue,
  ImpactAnalysisRequest,
  ImpactAnalysisSpecImpact,
  ImpactAnalysis,
  VectorSearchRequest,
  VectorSearchResult,
  SCMCommitRecord,
  SCMStatusSummary,
  SCMBranchInfo,
  SCMPushResult,
  SCMCommitLogEntry,
  SecurityScanRequest,
  SecurityScanResult,
  VulnerabilityReport,
  SyncStatus,
  SyncOptions,
  SystemAnalytics,
  CreateSpecRequest,
  CreateSpecResponse,
  GetSpecResponse,
  UpdateSpecRequest,
  ListSpecsParams,
  TestCoverage,
  TestPlanRequest,
  TestPlanResponse,
  TestSpec,
  TestExecutionResult,
  CodeChangeProposal,
  CodeChangeAnalysis,
  TraversalQuery,
  EntityTimelineEntry,
  EntityTimelineResult,
  RelationshipTimelineSegment,
  RelationshipTimeline,
  StructuralNavigationEntry,
  ModuleChildrenResult,
  ModuleHistoryOptions,
  ModuleHistoryEntitySummary,
  ModuleHistoryRelationship,
  ModuleHistoryResult,
  ImportEntry,
  ListImportsResult,
  DefinitionLookupResult,
  DependencyAnalysis,
  CommitPRRequest,
  CommitPRResponse,
  GraphSearchRequest,
  GraphSearchResult,
  GraphExamples,
} from '@memento/shared-types';

// Note: All other types have been moved to @memento/shared-types/core-types.ts
// This file now only contains imports and re-exports for backward compatibility
